import globalS from "/styles/globals.css";
import S from "/styles/page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={globalS.body}>
        <Banner content="현대카드" />
        <Banner content="삼성카드" />
        {children}
      </body>
    </html>
  );
}

export const Banner = (props) => {
  return <p className={S.cartSub}>🍀 {props.content} 무이자 이벤트 중 🍀</p>;
};
