import globalS from "/styles/globals.css";
import S from "/styles/page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={globalS.body}>
        <p className={S.cartSub}>🍀 현대카드 무이자 이벤트 중 🍀</p>
        {children}
      </body>
    </html>
  );
}
